apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-productpage
spec:
  resources:
    - name: git
      type: git
    - name: image
      type: image
  params:
    - description: The location of the repo to be updated
      name: GITOPS_REPO
      type: string
      default: https://github.com/ibm-garage-cph/gitops-bookinfo
    - description: The path to the deployment yaml where we apply the change
      name: DEPLOYMENT_FILE
      type: string
      default: ./prod/deployment-productpage-v2.yaml
  tasks:
    - name: build-push
      taskRef:
        name: build-push
      resources:
        inputs:
          - name: git
            resource: git
          - name: image
            resource: image
    - name: gitops-task
      taskRef:
        name: gitops-task
      runAfter: [build-push]
      resources:
        inputs:
          - name: git
            resource: git
          - name: image
            resource: image
      params:
        - name: GITOPS_REPO
          value: $(params.GITOPS_REPO)
        - name: DEPLOYMENT_FILE
          value: $(params.DEPLOYMENT_FILE)
